- name: install httpd
  hosts: web
  become: yes
  tasks:
  - name: install httpd
    ansible.builtin.package:
    - name: httpd
      state: installed

  - name: start http
    ansible.builtin.service:
    - name: start http
      state: started